/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.cadastro_pessoas;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Ryzen
 */


public class CadPessoas extends javax.swing.JFrame {

    /**
     * Creates new form CadPessoas
     */
    
    public String id_pessoa;
    
    public CadPessoas() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        TxtNome = new javax.swing.JLabel();
        TxtSobrenome = new javax.swing.JLabel();
        RecebeSobrenome = new javax.swing.JTextField();
        RecebeNome = new javax.swing.JTextField();
        BotaoCadastro = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        TabelaPessoas = new javax.swing.JTable();
        BotaoTelaEditar = new javax.swing.JButton();
        BotaoDeletar = new javax.swing.JButton();
        BotaoCancelar = new javax.swing.JButton();
        BotaoTelaPesquisar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowActivated(java.awt.event.WindowEvent evt) {
                formWindowActivated(evt);
            }
        });

        TxtNome.setText("Nome");

        TxtSobrenome.setText("Sobrenome");

        BotaoCadastro.setText("Cadastrar");
        BotaoCadastro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCadastroActionPerformed(evt);
            }
        });

        TabelaPessoas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "ID", "Nome", "Sobrenome"
            }
        ));
        TabelaPessoas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TabelaPessoasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TabelaPessoas);

        BotaoTelaEditar.setText("Editar");
        BotaoTelaEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoTelaEditarActionPerformed(evt);
            }
        });

        BotaoDeletar.setText("Deletar");
        BotaoDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoDeletarActionPerformed(evt);
            }
        });

        BotaoCancelar.setText("Cancelar");
        BotaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoCancelarActionPerformed(evt);
            }
        });

        BotaoTelaPesquisar.setText("Pesquisar");
        BotaoTelaPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BotaoTelaPesquisarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(TxtNome)
                    .addComponent(TxtSobrenome)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(BotaoCadastro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(BotaoCancelar, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(BotaoTelaEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoTelaPesquisar, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(RecebeNome, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                    .addComponent(RecebeSobrenome))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jScrollPane1)
                    .addComponent(BotaoDeletar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 336, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addComponent(TxtNome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RecebeNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(TxtSobrenome)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(RecebeSobrenome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BotaoCadastro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(BotaoCancelar)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BotaoDeletar)
                    .addComponent(BotaoTelaEditar)
                    .addComponent(BotaoTelaPesquisar))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void BotaoCadastroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCadastroActionPerformed
        // TODO add your handling code here:
        
        try {
            Connection conexao = null;
            PreparedStatement statement = null;
            
            String url = "jdbc:mysql://localhost:3306/pessoas";
            String usuario = "root";
            String senha = "";
            
            conexao = DriverManager.getConnection (url, usuario, senha) ;
            String sql = "INSERT INTO pessoas_cadastradas(nome_pessoa, sobrenome_pessoa) VALUES (?, ?)";
            
            statement = conexao.prepareStatement(sql);
            statement.setString(1, RecebeNome.getText());
            statement.setString(2, RecebeSobrenome.getText());
            statement.executeUpdate();
            JOptionPane.showMessageDialog(null, "Cadastro concluido!");
            
            RecebeNome.setText("");
            RecebeSobrenome.setText("");
            System.out.println("PASS");
            
            // TODO add your handling code here:
        } catch (SQLException ex) {
            System.out.println(ex);
        }
    }//GEN-LAST:event_BotaoCadastroActionPerformed

    private void BotaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoCancelarActionPerformed
        // TODO add your handling code here:
        RecebeNome.setText("");
        RecebeSobrenome.setText("");
    }//GEN-LAST:event_BotaoCancelarActionPerformed

    private void formWindowActivated(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowActivated
        // TODO add your handling code here:
        carregarDados();
    }//GEN-LAST:event_formWindowActivated

    private void TabelaPessoasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TabelaPessoasMouseClicked
        // TODO add your handling code here:
        int linhaSelecionada = TabelaPessoas.getSelectedRow();
        
        Object id = TabelaPessoas.getValueAt(linhaSelecionada, 0);
        
        id_pessoa = String.valueOf(id);
    }//GEN-LAST:event_TabelaPessoasMouseClicked

    private void BotaoDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoDeletarActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            
            int resposta = JOptionPane.showConfirmDialog(null, "Estas informações não retornarão deseja continuar?", "Confirmação", JOptionPane.YES_NO_OPTION);
            
            if(resposta == 0){
                
            Connection conexao = null;
            PreparedStatement stat = null;
            
            String url = "jdbc:mysql://localhost:3306/pessoas";
            String usuario = "root";
            String senha = "";
            
            conexao = DriverManager.getConnection (url, usuario, senha) ;
            String sql = "DELETE from pessoas_cadastradas where id_pessoas = ?";
            
            stat = conexao.prepareStatement(sql);
            stat.setString(1, id_pessoa);
            stat.executeUpdate();
            
            carregarDados();
            
            }
        } catch (SQLException ex) {
            System.out.println(ex.getMessage());
        }
    }//GEN-LAST:event_BotaoDeletarActionPerformed

    private void BotaoTelaEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoTelaEditarActionPerformed
        // TODO add your handling code here:
        EditPessoa edita = new EditPessoa();
        edita.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoTelaEditarActionPerformed

    private void BotaoTelaPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BotaoTelaPesquisarActionPerformed
        // TODO add your handling code here:
        PesPessoa pesquisa = new PesPessoa();
        pesquisa.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_BotaoTelaPesquisarActionPerformed

    public class DatabaseConnection {
        public static Connection getConnection() {
            Connection connection = null;
            try {
                String url = "jdbc:mysql://localhost:3306/pessoas";
                String user = "root";
                String password = "";

                connection = DriverManager.getConnection(url, user, password);
            } catch (SQLException e) {
                System.out.println("Erro ao conectar: " + e.getMessage());
            }
            return connection;
        }
    }
    
    private void carregarDados() {
        DefaultTableModel modelo = (DefaultTableModel) TabelaPessoas.getModel();
        modelo.setRowCount(0); // Limpa a tabela antes de adicionar novos dados

        String sql = "SELECT * FROM pessoas_cadastradas"; // Substitua pelo nome da sua tabela

        try (Connection conn = DatabaseConnection.getConnection();
             PreparedStatement stmt = conn.prepareStatement(sql);
             ResultSet rs = stmt.executeQuery()) {

            // Adicionar colunas ao modelo, se necessário
            modelo.setColumnIdentifiers(new String[]{"ID", "Nome", "Sobrenome"}); // Colunas da tabela

            // Adiciona as linhas à tabela
            while (rs.next()) {
                modelo.addRow(new Object[]{
                    rs.getInt("id_pessoas"),       // Substitua pelos nomes das colunas do banco
                    rs.getString("nome_pessoa"),
                    rs.getString("sobrenome_pessoa")
                });
            }

        } catch (SQLException e) {
            System.out.println("Erro ao carregar dados: " + e.getMessage());
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CadPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CadPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CadPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CadPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CadPessoas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BotaoCadastro;
    private javax.swing.JButton BotaoCancelar;
    private javax.swing.JButton BotaoDeletar;
    private javax.swing.JButton BotaoTelaEditar;
    private javax.swing.JButton BotaoTelaPesquisar;
    private javax.swing.JTextField RecebeNome;
    private javax.swing.JTextField RecebeSobrenome;
    private javax.swing.JTable TabelaPessoas;
    private javax.swing.JLabel TxtNome;
    private javax.swing.JLabel TxtSobrenome;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
